services:
  palo-certs:
    build: .
    image: paloalto-letsencrypt:latest
    container_name: palo-certs
    env_file: .env
    volumes:
      - ./certs:/app/certs
      - ./config:/app/config
      - ./logs:/app/logs
    restart: unless-stopped
