services:
  palo-certs:
    build: .
    container_name: palo-certs
    volumes:
      - ./certs:/app/certs
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - PALO_HOST=${PALO_HOST}
      - PALO_USER=${PALO_USER}
      - PALO_PASS=${PALO_PASS}
    restart: unless-stopped
