name: Trigger auto deployment for paloalto-letsencrypt

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/paloalto-letsencrypt-AutoDeployTrigger-957f1d99-57c6-4c10-a127-f7e5b49c5337.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PALOALTOLETSENCRYPT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PALOALTOLETSENCRYPT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PALOALTOLETSENCRYPT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: "./Dockerfile"
          registryUrl: mwheatfill.azurecr.io
          registryUsername: ${{ secrets.PALOALTOLETSENCRYPT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PALOALTOLETSENCRYPT_REGISTRY_PASSWORD }}
          containerAppName: paloalto-letsencrypt
          resourceGroup: rg-containers
          imageToBuild: mwheatfill.azurecr.io/paloalto-letsencrypt:${{ github.sha }}
